export const SET_QUIZ = 'SET_QUIZ'

export const SET_FINISHED_QUIZ = 'SET_FINISHED_QUIZ'

export const SET_ALL_FINISHED_QUIZ = 'SET_ALL_FINISHED_QUIZ'

export const SET_QUESTION_STATUS = 'SET_QUESTION_STATUS'

export const SET_ERROR = 'SET_ERROR'

export const SET_LOADING = 'SET_LOADING'

export const SET_CURRENT_QUIZ = 'SET_CURRENT_QUIZ'

export const SET_INDEX = 'SET_INDEX'